### PR TITLE
Add optgroup support

### PR DESCRIPTION
**Pull request by davea**
Uses the `::before` pseudo-element so as not to break keyboard up/down
navigation.

optgroups

### CODE REVIEW

**Comment by davea** [comment]
Getting input from somebody who actually uses a screen reader is probably a good idea. Under the assumption that the browser is more likely to render the `<optgroup>` elements accurately in a screen reader, would it be a good idea to hide our custom markup from the screen reader and let it read the native `<select>` instead?

**Comment by zarino** [comment]
> would it be a good idea to hide our custom markup from the screen reader and let it read the native `<select>` instead?

That is an option, although it would mean the user would miss out on things like the `presets` (if they are present).

**Comment by dracos** [comment]
Just tested NVDA. In a normal select, it reads out the label the first time you move into an optgroup and *if you've expanded the select* says number and level:
 "Animal fouling grouping, footway/carriageway, [1 of 2, level 2]"
 "Park/open space, [2 of 2, level 2]"

One problem is that if there are items not in an optgroup at the top (as we do have sometimes when there's a mix), then it doesn't mention level, so to the listener it's as if you've reached the end when you get to the end of that section, ie. it says "11 of 11" (before the first optgroup section).

With a multiple select, it doesn't tell you it's a multiple select at all that I can tell, which means you probably navigate it as if it's a normal one and only ever select one item. So it's possible our plugin here makes that better, in that it is clearer they are separate selectable options.

So, what it currently sounds like is quite similar. What I'd go for now, in the interest of not holding this up further, would be to have the optgroup added to the start of each line, only visually present on the first item?

**Comment by dracos** [comment]
Or use a fieldset/legend instead? That seems nice, and standard.

**Comment by dracos** [comment]
Have pushed something to put the before on all menu items, but visually hidden on all except the first of each optgroup.

**Pull request merged**
