### PR TITLE
Added an optional wrapper

### PR DESCRIPTION
**Pull request by lucascumsille**
Fixes part of: https://github.com/mysociety/fixmystreet/pull/4560

This wrapper wraps the following elements:
-label
-multi-select-container
-select

This should help having a better control of the layout of the form.

### CODE REVIEW

**Comment by lucascumsille** [comment]
@dracos not sure why, but I'm having issues making the `prependTo` working. Any ideas how I can fix that?
Basically the whole `prependFormElements` is not working, I know is being called if I console.log the elements, but they just don't move.

**Comment by lucascumsille** [comment]
Thanks @dracos Sorry I know this is an old one:
For this PR I intended to do this:
https://github.com/mysociety/fixmystreet/pull/4560#issuecomment-1700714459 Which was basically added an optional configuration to the whole select stuff in container so we can have a better of the styling/layout especially when we have two or more select elements next to each other.

> The issue in https://github.com/mysociety/fixmystreet/commit/3bab3766a01c361b671c89564966a126e516aa19?w=1#diff-e4c184a6c747ed805c439d3ab007bd3b1da6a9d8a88482a41e6d8bb49dfe00f6R118-R125 was that you wanted to wrap each individual checkbox "menu item" in a div (containing the label/input), which was tricky to do in that code, and this doesn't change?

mmm not really, as far as I remember I don't think wrapping the "menu item" was the intention of that commit, rather to have each select element + multi-select + label wrapped in an individual container. That commit solved the issue that when going to an around page we have the first `.report-list-filters` element that has two selects + labels + multi-select so controlling the layout was quite tricky.

Let me know if I misunderstood this or you think there is a better method.

**Comment by dracos** [comment]
The default gov-uk styling, as I understand it, needs HTML something like `<div class="govuk-checkboxes__item"> <input class="govuk-checkboxes__input" type="checkbox" name="fixed" id="form_fixed" value="1"> <label for="form_fixed" class="govuk-label govuk-checkboxes__label">This problem has been fixed</label> </div>`. The commit https://github.com/mysociety/fixmystreet/commit/3bab3766a01c361b671c89564966a126e516aa19 set menuItemHTML to be a `<div class="govuk-checkboxes__item">` and then had that extra code to add the label as a child of that (as previously the menuItemHTML was a label itself). So it was converting every checkbox in that manner, it wasn't adding a wrapper around the whole thing?

What this change does is wrap the whole thing - if that provides you with what you need to style it, then okay, but wrapping the whole thing doesn't have to change this code at all, unless I've misunderstood something - you can wrap it in whatever calling code you want, so no change to this code would be needed? If you have two selects in the FMS code, why can't you wrap them there? You'd only need to change this code to alter something internal it ie. altering how every menu item is generated/wrapped, which is what I thought you wanted/needed to do.

**Comment by lucascumsille** [comment]
@dracos Sorry I totally overcomplicated it. I'll wrap the select on FMS and dropped this PR.

Closed: No need to include a wrapper on the configuration, because it can be added manually to the select element via HTML.

**Comment by lucascumsille** [comment]
@dracos Sorry I totally overcomplicated it. I'll wrap the select on FMS and dropped this PR.

Closed: No need to include a wrapper on the configuration, because it can be added manually to the select element via HTML.

**Pull request closed without merging**
